# Generated by Django 4.0 on 2022-01-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0, null=True)),
                ('user_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Work User',
                'verbose_name_plural': 'Work User',
                'db_table': 'work_user',
            },
        ),
    ]
