# Generated by Django 4.0 on 2022-01-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_workprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='host',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='user_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
