# Generated by Django 4.0 on 2022-01-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_workstation_description_alter_workstation_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstation',
            name='host',
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='user_name',
        ),
    ]
