# Generated by Django 4.0 on 2022-01-06 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_workstation_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprocess',
            name='work_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.workuser'),
        ),
    ]
