# Generated by Django 4.0 on 2022-01-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_rename_user_key_workuser_company_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workuser',
            old_name='company_data',
            new_name='company_data_id',
        ),
    ]
